name: valiq_editor_demo
description: VALIQ Editor Demo for APEXIVE Agency
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  faker: ^2.1.0
  feather_icons: ^1.2.0
  firebase_core: ^2.23.0
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  logger: ^2.0.2+1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  file_picker: ^6.1.1
  scroll_to_index: ^3.0.1
  google_fonts: ^6.1.0
  flutter_color: ^2.1.0
  flex_color_picker: ^3.3.0
  qr_flutter:
    git:
      url: https://github.com/IZriouil/qr.flutter.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/